# Generated by Django 3.2.13 on 2022-05-31 04:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gauges',
            fields=[
                ('gauge_id', models.CharField(max_length=10)),
                ('gauge_location', models.CharField(max_length=50)),
                ('gauge_tz', models.CharField(max_length=50)),
                ('gauge_pk', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='observations',
            fields=[
                ('observation_stage', models.FloatField()),
                ('observation_flow', models.FloatField()),
                ('observation_time', models.DateTimeField()),
                ('observation_pk', models.AutoField(primary_key=True, serialize=False)),
                ('observation_gauge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floodlook_looker.gauges')),
            ],
        ),
        migrations.CreateModel(
            name='forecast',
            fields=[
                ('forecast_stage', models.FloatField()),
                ('forecast_flow', models.FloatField()),
                ('forecast_time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('forecast_time', models.DateTimeField()),
                ('forecast_pk', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_gauge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floodlook_looker.gauges')),
            ],
        ),
    ]
