# Generated by Django 3.2.13 on 2022-05-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodlook_looker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='forecast_flow',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_stage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='observation_flow',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='observation_stage',
            field=models.FloatField(null=True),
        ),
    ]
